version: '3.8'

services:
  core:
    build: ./core
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - AUTH_SERVICE_URL=http://auth:9000

  auth:
    build: ./auth
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis

  telegram:
    build: ./telegram-client
    depends_on:
      - core
      - auth
    environment:
      - CORE_SERVICE_URL=http://core:8080
      - AUTH_SERVICE_URL=http://auth:9000

  web:
    build: ./web-client
    ports:
      - "3000:3000"
    depends_on:
      - core
      - auth

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: testingdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
